using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Oucc.AotCsv.Generator.Utility;

namespace Oucc.AotCsv.Generator;

[Generator(LanguageNames.CSharp)]
public partial class SerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeContext = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Oucc.AotCsv.Attributes.CsvSerializableAttribute",
            static (_, _) => true,
            static (context, _) => context);

        var source = attributeContext.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(source, static ( context, source ) =>
        {
            var (attributeContext, compilation) = source;

            Emit(context, attributeContext, compilation);
        });
    }

    private static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source, Compilation compilation)
    {
        var targetSymbol = (INamedTypeSymbol)source.TargetSymbol;

        var builder = new StringBuilder();
        var reference = new ReferenceSymbols(compilation);

        builder.Append("""
            // <auto-generated/>

            """);

        if (!targetSymbol.ContainingNamespace.IsGlobalNamespace)
            builder.AppendFormatted($"namespace {targetSymbol.ContainingNamespace.ToString()};\n");

        builder.AppendFormatted($$"""

            partial {{(targetSymbol.TypeKind == TypeKind.Class ? "class" : "struct")}} {{targetSymbol.Name}} : global::Oucc.AotCsv.ICsvSerializable<{{targetSymbol.Name}}>
            {
                static void global::Oucc.AotCsv.ICsvSerializable<{{targetSymbol.Name}}>.WriteHeader(global::System.IO.TextWriter writer, global::Oucc.AotCsv.CsvSerializeConfig context)
                {
            """);

        CreateHeaderCode(builder, targetSymbol);

        builder.AppendFormatted($$"""
                }

                static void global::Oucc.AotCsv.ICsvSerializable<{{targetSymbol.Name}}>.WriteRecord(global::System.IO.TextWriter writer, global::Oucc.AotCsv.CsvSerializeConfig config, {{targetSymbol.Name}} value)
                {
            """);

        CreateBodyCode(builder, targetSymbol, new ISymbol[0], reference);

        builder.Append("""
                }
            }

            """);

        context.AddSource(targetSymbol.Name + ".g.cs", builder.ToString());
    }

    class Comparer : IEqualityComparer<(GeneratorAttributeSyntaxContext, Compilation)>
    {
        public static readonly Comparer Instance = new Comparer();

        public bool Equals((GeneratorAttributeSyntaxContext, Compilation) x, (GeneratorAttributeSyntaxContext, Compilation) y)
        {
            return x.Item1.Equals(y.Item1);
        }

        public int GetHashCode((GeneratorAttributeSyntaxContext, Compilation) obj)
        {
            return obj.Item1.GetHashCode();
        }
    }
}
